### ISSUE TITLE
Misbehavior when setting more than 8 routes

### ISSUE THREAD

**Issue by andrademf** [lsevero/franz#8]
If 8 or more routes are defined in the config file the component doesn't work as expected.

**What happen**
Requests are never replied nor timed out. No error are shown in the logs.
Only "404 not found" works.

**Steps to reproduce**
1. Set the config file with
```
:routes {
          "/test0/*"    {:get {:consumer {"group.id" "grp-test-0"}}}
          "/test1/*"    {:get {:consumer {"group.id" "grp-test-1"}}}
          "/test2/*"    {:get {:consumer {"group.id" "grp-test-2"}}}
          "/test3/*"    {:get {:consumer {"group.id" "grp-test-3"}}}
          "/test4/*"    {:get {:consumer {"group.id" "grp-test-4"}}}
          "/test5/*"    {:get {:consumer {"group.id" "grp-test-5"}}}
          "/test6/*"    {:get {:consumer {"group.id" "grp-test-6"}}}
          "/test7/*"    {:get {:consumer {"group.id" "grp-test-7"}}}
}
```
2. Request any defined route

**Comment by andrademf** [comment]
Setting the Jetty log level to debug it's possible to see the following message:
```
2021-05-26 16:17:45,148 [qtp998901309-35] DEBUG org.eclipse.jetty.io.WriteFlusher - ignored: WriteFlusher@592fd8ed{IDLE}->null
java.nio.channels.ClosedChannelException
	at org.eclipse.jetty.io.WriteFlusher.onClose(WriteFlusher.java:502)
	at org.eclipse.jetty.io.AbstractEndPoint.onClose(AbstractEndPoint.java:353)
	at org.eclipse.jetty.io.ChannelEndPoint.onClose(ChannelEndPoint.java:216)
	at org.eclipse.jetty.io.AbstractEndPoint.doOnClose(AbstractEndPoint.java:225)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:192)
	at org.eclipse.jetty.io.AbstractEndPoint.close(AbstractEndPoint.java:175)
	at org.eclipse.jetty.io.AbstractConnection.close(AbstractConnection.java:248)
	at org.eclipse.jetty.server.HttpChannelOverHttp.earlyEOF(HttpChannelOverHttp.java:234)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:1551)
	at org.eclipse.jetty.server.HttpConnection.parseRequestBuffer(HttpConnection.java:360)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:250)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by lsevero** [comment]
Indeed, if the number of producers and consumers are too big for clojure.core.async thread pool size some routes will become unresponsive.
This increasing the threadpool size with the java property `-Dclojure.core.async.pool-size=<number of routes>`. 
I've added a log/error about this problem when you have a large :routes section in the config file on v1.4.4.
